### ISSUE TITLE
Standardordner für Sephrasto Charaktere

### ISSUE THREAD

**Issue by Aeolitus** [Aeolitus/Sephrasto#9]
Isilda Amalia von Hartsteen bittet im DSAforum darum, dass es einen Standardordner geben soll, in den Charaktere gespeichert werden und von wo man sie laden kann.

Das hat das Problem, dass Sephrasto ja keine Installation hat, und somit kein Ordner angelegt würde. Das könnte man zwar immer beim Programmstart machen, aber was, wenn der User das gar nicht will? Die aktuelle Lösung ist etwas mühsam, aber dafür immerhin Minimalinvasiv am Rechner.

**Comment by Alchemist650** [comment]
Version 0.6.1 führt einen Standardordner "Sephrasto" im /home/user/ Verzeichnis mit einer Sephrasto.ini ein. Es gibt die Möglichkeit, den Charakterordner und Regelordner unter einem anderen Pfad zu haben. Ändert man diese Pfade, werden Charaktere & Regeln zwar aus diesen Ordnen geholt, der Sephrasto Ordner muss aber zwangsweise im Hauptverzeichnis des Benutzers liegen und verfehlt damit ein wenig den Zweck eigene Pfade zu setzen.

Expected Behaviour: Es wird im Hauptverzeichnis des Benutzers eine Sephrasto.ini (Windows) / .Sephrasto (Linux) angelegt, welche die Informationen enthält wo der Charakter und der Regel Pfad ist.
Standard bleibt: "/home/user/Sephrasto/Charaktere".

**Comment by Alchemist650** [comment]
Könnte die Sephrasto.ini auf nicht Windows System nach /home/user/.config/Sephrasto/Sephrasto.ini verschoben werden?

**Comment by brzGatsu** [comment]
Ich schließe mal weil der initiale Request abgeschlossen ist. Falls jemand noch ne Idee zu Alchemists Vorschlag haben sollte einfach melden.
